[package]
name = "tonbi"
version = "0.1.0"
edition = "2021"
authors = ["highhi <kazu8160@gmail.com>"]
description = "A simple and intuitive CLI framework for Rust"
license = "MIT"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
